version: 2
# .goreleaser.yml
project_name: go-git-providers

# This is a library so we don't have any build targets, but having goreleaser automatically
# generate release notes for us is nice.
builds:
  - id: go-git-providers
    skip: true
