---
name: e2e-gitlab

"on":
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: ["*"]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Start Provider instances
        run: make start-provider-instances-gitlab
      - name: Run tests [gitlab]
        run: make test-e2e-gitlab
