name: lint

on:
  workflow_dispatch:
  push:
    branches-ignore:
      # Do not push events to branches matching refs/heads/main
      - 'main'
    tags-ignore: [ '*' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Run Revive Action
        uses: docker://morphy/revive-action:v2
        with:
          # Path to your Revive config within the repo (optional)
          config: revive/config.toml



