name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      # Do not push events to branches matching refs/heads/main
      - 'main'
    tags-ignore: [ '*' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run Revive Action
        uses: docker://morphy/revive-action:v2
        with:
          # Path to your Revive config within the repo (optional)
          config: revive/config.toml



