name: lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      # Do not push events to branches matching refs/heads/main
      - 'main'
    tags-ignore: [ '*' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Run Revive Action
        uses: docker://morphy/revive-action:v2
        with:
          # Path to your Revive config within the repo (optional)
          config: revive/config.toml



